- src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
- src/NServiceBus.SqlServer.UnitTests/SqlConnectionFactoryConfigTests.cs
- src/NServiceBus.SqlServer/AmbientTransactionReceiveStrategy.cs
- src/NServiceBus.SqlServer/Config/SqlConnectionFactoryConfig.cs
- src/NServiceBus.SqlServer/Config/SqlServerTransportFeature.cs
- src/NServiceBus.SqlServer/CustomSqlConnectionFactory.cs
- src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
- src/NServiceBus.SqlServer/NativeTransactionReceiveStrategy.cs
- src/NServiceBus.SqlServer/NoTransactionReceiveStrategy.cs
- src/NServiceBus.SqlServer/QueuePurger.cs
- src/NServiceBus.SqlServer/ReceiveStrategyFactory.cs
- src/NServiceBus.SqlServer/SqlServerMessageSender.cs
- src/NServiceBus.SqlServer/SqlServerQueueCreator.cs
- src/NServiceBus.SqlServer/SqlServerSettingsExtensions.cs
*Make usage of NHibernate compatible with `SET NOCOUNT ON` DB-wide setting #112* issue shows how NOCOUNT server setting can break the NHibernate persistence. It was solved by injecting NHibernate's DriverConnectionProvider, that fixes connections immediately after their opening. However, when SQL Server transport is used, and the same database is used for Timeouts persistence and SQL Transport, it can happen that connections opened for transport can be used by Timeouts persistence routines.
Solution: allow injection of custom SQL connections' factories, like NHibernate does. Such factories can, for example, send `SET NOCOUNT OFF` command immediately after opening the connection.
> SqlConnections should be created with factory

- src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
- src/NServiceBus.SqlServer.AcceptanceTests/TransactionScope/When_customizing_scope_isolation_level.cs
- src/NServiceBus.SqlServer.AcceptanceTests/TransactionScope/When_using_scope_timeout_greater_than_machine_max.cs
- src/NServiceBus.SqlServer/SqlServerTransport.cs
- src/NServiceBus.SqlServer/SqlServerTransportSettingsExtensions.cs
This change allows to set transaction scope options (isolation level and timeout) on transport level for SQL Server transport.
PR with analogous change for the MSMQ transport: particular/NServiceBus#3249.
Doco PR (WIP): particular/docs.particular.net#1026.
> Configure transaction scope options on SQL Server transport level

- src/NServiceBus.SqlServer/Configuration/SqlConnectionFactory.cs
- src/NServiceBus.SqlServer/Receiving/MessagePump.cs
- src/NServiceBus.SqlServer/Receiving/QueueCreator.cs
- src/NServiceBus.SqlServer/Receiving/ReceiveWithNoTransaction.cs
- src/NServiceBus.SqlServer/Receiving/ReceiveWithReceiveOnlyTransaction.cs
- src/NServiceBus.SqlServer/Receiving/ReceiveWithSendsAtomicWithReceiveTransaction.cs
- src/NServiceBus.SqlServer/Receiving/ReceiveWithTransactionScope.cs
- src/NServiceBus.SqlServer/Sending/MessageDispatcher.cs
- src/NServiceBus.SqlServer/TaskEx.cs
@Particular/tf-async-transport please review
Also fixed the message pump. I think it is wrong to await the continuation task. You should be able to ignore the potentially synchronously executed continuation.
> ConfigureAwait(false)

- src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
- src/NServiceBus.SqlServer.AcceptanceTests/TimeToBeReceived/When_queue_contains_expired_messages.cs
- src/NServiceBus.SqlServer/Receiving/ReceiveWithReceiveOnlyTransaction.cs
- src/NServiceBus.SqlServer/Receiving/ReceiveWithSendsAtomicWithReceiveTransaction.cs
- src/NServiceBus.SqlServer/Receiving/ReceiveWithTransactionScope.cs
SQL Server transport does not currently commit the transaction when it retrieves an expired message from the queue. This results in expired messages being processed indefinitely. This is clearly a regression from V2.
This PR addresses the problem in the same way as V2 (by committing the transaction).
> Correctly remove expired messages from queue

- src/NServiceBus.SqlServer/obsoletes.cs
Connects to https://github.com/Particular/NServiceBus.SqlServer/issues/148
This adds the `UseConnectionString` method to the obsoletes so intellisense still shows the method but compiling results in an error.
> Add UseConnectionString to obsoletes

- src/NServiceBus.SqlServer.AcceptanceTests/When_in_native_transaction_mode.cs
- src/NServiceBus.SqlServer.UnitTests/AdaptiveExecutorSimulator/RealSimulator.cs
- src/NServiceBus.SqlServer/Config/PurgingConfig.cs
- src/NServiceBus.SqlServer/ExpiredMessagesPurger.cs
- src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
- src/NServiceBus.SqlServer/PurgeExpiredMessagesParams.cs
- src/NServiceBus.SqlServer/SqlServerPollingDequeueStrategy.cs
- src/NServiceBus.SqlServer/SqlServerQueueCreator.cs
- src/NServiceBus.SqlServer/TableBasedQueue.cs
Taskforce: @MarcinHoppe @tmasternak 
SQL Server transport discards expired messages when it receives them from the queue table. If the endpoint is down for some time and expired messages build up in the queue, the endpoint will need to receive all of these messages in order to discard them.
The solution is to purge expired messages at the startup of the endpoint and then periodically after every 5 minutes. The purging is done in batches, 10000 rows at a time until there are no more expired messages in the queue.
Users of the SQL Server transport receiving messages with `TimeToBeReceived` attribute.
When there is a backlog of expired messages in the queue table, then upon the startup of the endpoint the log will contain the following line for each expired message:
`Message with ID=<Message …
> V2: SQL Server transport now periodically purges expired messages

- src/NServiceBus.SqlServer/Configuration/SettingsKeys.cs
- src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacySqlServerTransportInfrastructure.cs
- src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
- src/NServiceBus.SqlServer/Queuing/Message.cs
- src/NServiceBus.SqlServer/Queuing/MessageParser.cs
- src/NServiceBus.SqlServer/Queuing/Sql.cs
- src/NServiceBus.SqlServer/Queuing/TableBasedQueue.cs
- src/NServiceBus.SqlServer/Receiving/ExpiredMessagesPurger.cs
- src/NServiceBus.SqlServer/Receiving/MessagePump.cs
- src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
Taskforce: @MarcinHoppe @tmasternak 
In the actual versions (V2 & V3) of the transport [TTBR messages](http://docs.particular.net/nservicebus/messaging/discard-old-messages) are handled by endpoint process, this means thjat if the input queue is load with a lot of expired messages the endpoint will waste a lot of time at startup dealing with expired messages before being able to start consuming non expired ones.
We should handle such a scenario better. /cc @tmasternak @ramonsmits 
Inception: https://github.com/Particular/CustomerSuccess/issues/166
> V3: SQL Server transport now periodically purges expired messages

- src/NServiceBus.SqlServer.AcceptanceTests/MultiSchema/When_custom_schema_configured_with_bracketed_transport_discriminator.cs
- src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
- src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
- src/NServiceBus.SqlServer.UnitTests/QueueAddressTests.cs
- src/NServiceBus.SqlServer/Addressing/QueueAddress.cs
- src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
Connects to #155 
This ensures the schema name in the queue address is escaped to help distinguish it from other components (e.g. catalog) when we add them in the future.
> Escape schema name in queue address

- GitVersionConfig.yaml
As being discussed here:
https://gitter.im/GitTools/GitVersion?at=5707bb02c65c9a6f7f27e913
With @danielmarbach, there is an issue with a Pull Request merge message causing an unrequired bump in the minor version number in this repository.
By making this change, you can prevent that from happening.
Once you have tagged the repo at 3.1.0, you can remove this change in case you actually want this going forward.
**NOTE:** in order to prove that this is working, make sure to empty the cached version number folder, just in case you are seeing pre-calculated versions.  You should always do this when making a change to the GitVersionConfig.yaml file, as you can get previous results.  The cache folder is here:
`.git\gitversion_cache`
in the repo checkout folder.
Hope this helps!
> Prevent bumping of version on develop branch from commit message

- src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
- src/NServiceBus.SqlServer.UnitTests/Sending/MessageDispatcherTests.cs
- src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
- src/NServiceBus.SqlServer/Sending/MessageDispatcher.cs
- src/NServiceBus.SqlServer/Sending/TableBasedQueueDispatcher.cs
- src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
Connects to https://github.com/Particular/NServiceBus.SqlServer/issues/181
In order to prevent duplicate publishes when subscription store contains old V2 (schema-less) entries after upgrading publisher to V3.
This PR lacks proper unit testing of the deduplication behavior. This cannot be done currently because the dispatcher output (table queue) cannot be mocked. 
We should discuss unit testing the dispatcher before merging this.
> Deduplicate publish operations based on message ID and queue address

- src/NServiceBus.SqlServer/Receiving/MessagePump.cs
Connects to https://github.com/Particular/PlatformDevelopment/issues/732
Fixes #214 
This will increase performance of receives in order of magnitude on high latency scenarios but also low latency scenarios. On my machine I saw up to 6 times more throughput with Azure SQL S3.
Deeper analysis have shown that the `SqlConnection` constructor surrounded with a `TransactionScope` will do very costly operations synchronously on the calling thread such as [connection pooling](http://referencesource.microsoft.com/#System.Data/System/Data/ProviderBase/DbConnectionFactory.cs,208) and DTC enlistment.
Uses Sql.cs and MessageParser.cs from #211 
```
internal class Program
{
private static void Main(string[] args)
{
var receives = new ConcurrentDictionary<Task, Task>();
var stopwatch = …
```
> InnerReceive yields to enforce asynchronous continuation to avoid costly synchronous connection pooling and enlistment on pump task.

- src/NServiceBus.SqlServer/Receiving/ReceiveWithTransactionScope.cs
- src/NServiceBus.SqlServer/Sending/TableBasedQueueDispatcher.cs
Closing the SQL connection before invoking the pipe allows other things in the pipe (e.g. persistence) that use the same `TransactionScope` to open their connections without necessarily escalating to DTC (if both connections have the same connection string). The flow would be following:
1. Create `TransactionScope`
1. Open transport connection
1. Receive message
1. Close transport connection
1. Execute the pipe
1. Open persistence connection
1. Handle the message
1. Enqueue message to be sent (batching)
1. Open immediate dispatch `TransactionScope`
1. Open immediate dispatch connection
1. Send the message
1. Close the immediate dispatch connection
1. Dispose immediate dispatch `TransactionScope`
1. Close persistence connection
1. Open batch dispatch connection
1. Send batched messages
1. …
> Early closing of SQL connection in the ambient transaction mode.

- src/NServiceBus.SqlServer/Receiving/MessagePump.cs
Connects to https://github.com/Particular/NServiceBus/issues/3883
> Avoiding allocations with Task.ContinueWith by opting-in for delegate caching

- src/NServiceBus.SqlServer/SqlServerMessageSender.cs
- src/NServiceBus.SqlServer/SqlServerPollingDequeueStrategy.cs
All versions of the SQL Server transport use string interpolation to assemble queue table names. Some inputs may come from untrusted sources, for instance the `ReplyToAddress` message header. This may allow attacker to craft a message in such a way that arbitrary SQL is executed on the database.
Attackers can use this vulnerability to force an NServiceBus endpoint to execute arbitrary SQL statements against the SQL Server database that stores its input queue.
The exploitation of this vulnerability requires that all of the conditions below are met at the same time:
1. An attacker must have the ability to send a malicious message to an endpoint OR an attacker must be able to modify a message that is in transit to an endpoint such that the `ReplyToAddress` header can be manipulated,
1. The …
> SQL injection vulnerability

- src/NServiceBus.SqlServer/Queuing/MessageRow.cs
- src/NServiceBus.SqlServer/Queuing/Sql.cs
The current code base does always peek even expired messages, stream them from the server to the client, reads the data row into memory and the checks then if the message is expired. 
The benefit of the previous approach was that expired messages get deleted one by one by the receive loop and if there are leftovers the will be swept away by the purge expired messages cleaner. The drawback is that each and every messages needs to be loaded into the client, and the expired field needs to be checked.
With these changes expired messages will no longer add to the peek count and will no longer be peeked. They will only be swept away when the expired messages cleaner kicks in. The drawback here is that depending on the cleaner interval and the insertion rate the table might fill itself faster. …
> Peek only non expired messages

- src/NServiceBus.SqlServer/Queuing/Sql.cs
Connects to: #231 
Caveat first: This might be an esoteric change.
NO COUNT ON: Stops the message that shows the count of the number of rows affected by a Transact-SQL statement or stored procedure from being returned as part of the result set.
[Official MS statement](https://msdn.microsoft.com/en-us/library/ms189837.aspx)
> SET NOCOUNT ON prevents the sending of DONE_IN_PROC messages to the client for each statement in a stored procedure. For stored procedures that contain several statements that do not return much actual data, or for procedures that contain Transact-SQL loops, setting SET NOCOUNT to ON can provide a significant performance boost, because network traffic is greatly reduced.
Although detailed analysis[ from Dale on his blogs …
> Opt out from waiting for DONE_IN_PROC messages by setting NO COUNT ON for statements that don't need it

- src/NServiceBus.SqlServer.UnitTests/Sending/MessageDispatcherTests.cs
- src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacyTableBasedQueueDispatcher.cs
- src/NServiceBus.SqlServer/Sending/IQueueDispatcher.cs
- src/NServiceBus.SqlServer/Sending/MessageDispatcher.cs
- src/NServiceBus.SqlServer/Sending/TableBasedQueueDispatcher.cs
LINQ is expensive both in terms of allocs and time it takes. In the core we are trying to avoid it on hot paths.
> MessageDispatcher no longer uses LINQ and the allocations that come with it

- src/NServiceBus.SqlServer/Queuing/Sql.cs
This is a proposal of a change to the query used to purging expired messages from input queue. The changes were made only to the PurgeBatchOfExpiredMessages query and include:
* Inner select:
* Running in `READ UNCOMMITTED` (`NOLOCK` hint) and without `ORDER BY` on `RowVersion` column
* Returns `RowVersion` instead of `Id`
* Outer delete
* `WHERE` clause includes only `RowVersion`
Direct reason for changes was #308. Which reported a deadlock situation that was caused by `receiveMessage` and `purgeBatchOrExpiredMessages` queries running at the same time. Here is the diagram that was included in the original issue.
Process on the left is a `readMessage` operation that tries to delete row from input queue. To do that it needs exclusive IX lock both on clustered index `on RowVersion` column …
> [WIP] Better TTBR query

- src/NServiceBus.SqlServer.UnitTests/QueueAddressTests.cs
- src/NServiceBus.SqlServer/Addressing/QueueAddress.cs
Fixes #263 
I've monkey patched backwards compatibility tests and they are green as well.
/cc: @Particular/sqlserver-transport-maintainers
> Canonic form of tablename in transport address

- src/NServiceBus.SqlServer.UnitTests/ConnectionPoolValidatorTests.cs
- src/NServiceBus.SqlServer/Configuration/ConnectionPoolValidator.cs
Since there's no reason 0 can't be the minimum, there's no reason to bother the user if this setting isn't defined in the connection string.
@Particular/sqlserver-transport-maintainers please review.
> Don’t validate “Min Pool Size” (0 is fine) and give better warning

- src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacySqlServerTransportInfrastructure.cs
- src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
This removes the blocker for using SQL Server transport in raw mode (dispatcher + pump) as the previous code (Get) assumed the routing feature is enabled.
This does not change the behavior of normal endpoints.
> Use GetOrCreate for endpoint instances

- src/NServiceBus.SqlServer.IntegrationTests/When_checking_schema.cs
- src/NServiceBus.SqlServer.IntegrationTests/When_receiving_messages.cs
- src/NServiceBus.SqlServer.TransportTests/When_using_unicode_characters_in_headers.cs
- src/NServiceBus.SqlServer.UnitTests/APIApprovals.Approve.approved.txt
- src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacySqlServerTransportInfrastructure.cs
- src/NServiceBus.SqlServer/Queuing/MessageRow.cs
- src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
- src/NServiceBus.SqlServer/Queuing/TableBasedQueue.cs
- src/NServiceBus.SqlServer/Receiving/ExpiredMessagesPurger.cs
- src/NServiceBus.SqlServer/Receiving/MessagePump.cs
- src/NServiceBus.SqlServer/Receiving/SchemaVerification.cs
- src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
Fixes #340 
* Change the type of `Headers` column to `nvarchar(max)`
* Change the parameter type of the send command to `NVarchar`
* Add start-time validation (similar to `Expired` index check) that logs `WARN` if the `Headers` column type is `varchar` with CTA to change the type manually
> Support unicode headers

- src/CompatibilityTests/Facade_1.2/Facade_1.2.csproj
- src/CompatibilityTests/Facade_2.2/Facade_2.2.csproj
- src/CompatibilityTests/Facade_3.0/Facade_3.0.csproj
- src/CompatibilityTests/Facade_3.1/Facade_3.1.csproj
- src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
- src/NServiceBus.SqlServer.CompatibilityTests.Common/NServiceBus.SqlServer.CompatibilityTests.Common.csproj
- src/NServiceBus.SqlServer.CompatibilityTests/NServiceBus.SqlServer.CompatibilityTests.csproj
- src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
- src/NServiceBus.SqlServer.TransportTests/NServiceBus.SqlServer.TransportTests.csproj
- src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
allow tests to auto update and run on the correct version without needing to do a nuget update
> Usewildcardsfortests

- src/NServiceBus.SqlServer.IntegrationTests/When_receiving_messages.cs
- src/NServiceBus.SqlServer.IntegrationTests/When_using_ttbr.cs
- src/NServiceBus.SqlServer.TestHarness/NServiceBus.SqlServer.TestHarness.csproj
- src/NServiceBus.SqlServer.TestHarness/Program.cs
- src/NServiceBus.SqlServer.UnitTests/APIApprovals.Approve.approved.txt
- src/NServiceBus.SqlServer.sln
- src/NServiceBus.SqlServer/Configuration/SettingsKeys.cs
- src/NServiceBus.SqlServer/Queuing/Message.cs
- src/NServiceBus.SqlServer/Queuing/MessageRow.cs
- src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
- src/NServiceBus.SqlServer/Receiving/ExpiredMessagesPurger.cs
- src/NServiceBus.SqlServer/Receiving/MessagePump.cs
- src/NServiceBus.SqlServer/Receiving/ReceiveStrategy.cs
- src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
- src/NServiceBus.SqlServer/SqlServerTransportSettingsExtensions.cs
Fixes https://github.com/Particular/NServiceBus.SqlServer/issues/396
I decided to require explicit enabling of the purge-on-startup feature because in a scale-out environment purging on startup by default can cause problems.
> Expired message are only purged on startup and only if explicitly enabled

- src/NServiceBus.SqlServer.AcceptanceTests/Configuration/When_using_v2_configuration_app_config_for_schema_override.cs
- src/NServiceBus.SqlServer/Configuration/SettingsKeys.cs
- src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacySqlServerTransportInfrastructure.cs
- src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
This PR enables turning off connection string validation that checks if connection strings are not using unsupported parameters. 
This is needed to enable schema configuration in SC.Monitoring in the way consistent with current version of SC.
> Added option to turn off connection string validation

- src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
This prevents the conditional dependency from causing a problem if the transport package is used from a .NET Standard library.
This also bumps to latest patch version.
> Remove conditional dependency on System.Data.SqlClient

- src/NServiceBus.SqlServer.AcceptanceTests/App_Packages/NSB.AcceptanceTests.5.2.6/Retries/When_sending_to_slr.cs
In the NSB 5.2 there is a race condition where IWantToRunWhenBusStartsAndStops https://github.com/Particular/NServiceBus/blob/support-5.2/src/NServiceBus.Core/Unicast/UnicastBus.cs#L680. 
This causes the ignored test to fail in cases when messages is processed before the IWantToRunWhenBusStartsAndStops is initialized.
> Ignoring flaky test

- src/NServiceBus.SqlServer/Receiving/MessagePump.cs
- src/NServiceBus.SqlServer/Receiving/RepeatedFailuresOvertimeCurcuitBreaker.cs
I decided to use two values instead of a classic exponential back-off because:
* We don't ever want to wait for less than 1 second
* We don't ever want to wait for more than 10 seconds so that when the DB is back online we can quickly resume processing
Based on these bounds with exponential back-off we would only permit `c` values of 1,2 and 3 (2^3=8) which gives little benefit for the added complexity.
In case when `peek` works fine but `receive` fails (i.e. lack of `DELETE` permissions) the receive circuit breaker is going to be triggered. To prevent concurrently hammering the database the message pump has been modified to run only a single receive task at a time if the receive CB is triggered.
> Don't flood logs

- src/NServiceBus.SqlServer.AcceptanceTests/When_passing_custom_transaction_via_sendoptions.cs
- src/NServiceBus.SqlServer.AcceptanceTests/When_using_computed_message_body_column.cs
- src/NServiceBus.SqlServer.UnitTests/APIApprovals.Approve.approved.txt
- src/NServiceBus.SqlServer/Configuration/SettingsKeys.cs
- src/NServiceBus.SqlServer/DelayedDelivery/DelayedDeliveryQueueCreator.cs
- src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
- src/NServiceBus.SqlServer/Receiving/QueueCreator.cs
- src/NServiceBus.SqlServer/SendOptionsExtensions.cs
- src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
- src/NServiceBus.SqlServer/SqlServerTransportSettingsExtensions.cs
- src/Scripts/Create-Databases.sql
- src/Scripts/Reset-Database.sql
- Remove isolation level settings on the SqlTransport https://github.com/Particular/NServiceBus.SqlServer/issues/312
- Add startup diagnostics info https://github.com/Particular/NServiceBus.SqlServer/issues/404 
- Add an opt-in computed column for viewing message body https://github.com/Particular/NServiceBus.SqlServer/issues/445
- Allow passing an existing connection/transaction via send options https://github.com/Particular/NServiceBus.SqlServer/issues/444
- Ensure this fix has been included https://github.com/Particular/PlatformDevelopment/issues/1983
Docs https://github.com/Particular/docs.particular.net/pull/3861
> Maintenance release 1

- src/CompatibilityTests/Facade_3.0/Handler.cs
- src/CompatibilityTests/Facade_3.1/Handler.cs
- src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
There have been changes to `ApprovalTests` and `ApprovalUtilities` in versions 3.0.16. They are no longer targeting `.NETFramework 4.5` but `.NETFramework 4.6.1` and/or `.NETStandard 2.0`. That causes the build on master to fail for unit test which targets `.NETFramework 4.5`. 
In addition, this PR includes adding missing awaits in compatibility tests.
> Fix `master` builds

- src/NServiceBus.SqlServer.IntegrationTests/When_message_receive_takes_long.cs
- src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
- src/NServiceBus.SqlServer/Queuing/TableBasedQueue.cs
- src/NServiceBus.SqlServer/Receiving/MessagePump.cs
Fixes #481 
When peeking messages, we retrieve the count only up to the maximum concurrency level. This prevents the transport from effectively locking up if there are a lot of records to peek.
> Faster way to peek messages to retrieve message count

- src/NServiceBus.SqlServer.IntegrationTests/When_message_receive_takes_long.cs
- src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
- src/NServiceBus.SqlServer/Queuing/TableBasedQueue.cs
- src/NServiceBus.SqlServer/Receiving/MessagePump.cs
Fixes #481 
When peeking messages, we retrieve the count only up to the maximum concurrency level. This prevents the transport from effectively locking up if there are a lot of records to peek.
> SQL Server transport refuses to process messages if there are too many messages in the queue

- src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
Fixes https://github.com/Particular/KeepTheLightsOn/issues/269
I decided to reword the exception message and include the original error message instead of trying to be smart and parse the original exception message to detect the cause of the issue. 
The second options seemed to fragile as it would depend on the message of the exception thrown by the framework.
> Fixed startup check message and included original error.

- src/NServiceBus.SqlServer/DelayedDelivery/DelayedDeiveryTableBasedQueueFactory.cs
- src/NServiceBus.SqlServer/DelayedDelivery/DelayedMessageRow.cs
- src/NServiceBus.SqlServer/DelayedDelivery/DelayedMessageTable.cs
- src/NServiceBus.SqlServer/DelayedDelivery/StoreDelayedMessageCommand.cs
- src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
Fixes https://github.com/Particular/NServiceBus.SqlServer/issues/463
By using a timespan, the date conversion is done on the SQL instance that will also be checking for Due messages. Because the clock calculating the due date is the same clock that will be checking the due date, this will prevent clock drift from occurring with delayed delivery.
> Use TimeSpan instead of DateTime

- src/NServiceBus.SqlServer.AcceptanceTests/NativeTimeouts/When_configuring_delayed_delivery.cs
- src/NServiceBus.SqlServer/DelayedDelivery/DelayedDeliveryInfrastructure.cs
- src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
Warns for https://github.com/Particular/NServiceBus.SqlServer/issues/468 if `TimeoutManager` is used.
Replaces #497
> Warn not native

- src/NServiceBus.SqlServer/DelayedDelivery/StoreDelayedMessageCommand.cs
- src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
Fixes https://github.com/Particular/NServiceBus.SqlServer/issues/504
Alternative to https://github.com/Particular/NServiceBus.SqlServer/pull/508
The previous maintenance release switched from `DateTime` to `TimeSpan`. This PR breaks the `TimeSpan` into its corresponding parts and passes those parts to the underlying SQL layer that then uses those to do `DATEADD` calculations. 
The benefit of this approach is the following:
- The TimeSpan is preserved
- The TimeSpan parts are ints
- There is no interpretation in the SQL layer needed thus no logic is done in the SQL and the parameters can be passed as is
- It is aligned with how the [DATEADD function](https://docs.microsoft.com/en-us/sql/t-sql/functions/dateadd-transact-sql) works because it operates on date parts
- It is aligned with the …
> Fix DATEADD overflow by passing timespan parts to SQL layer

- src/NServiceBus.SqlServer/DelayedDelivery/DelayedMessageHandler.cs
- src/NServiceBus.SqlServer/DelayedDelivery/DelayedMessageTable.cs
- src/NServiceBus.SqlServer/TaskEx.cs
Fixes #501 
Alternative to https://github.com/Particular/NServiceBus.SqlServer/pull/502
This alternative makes sure that on the cancellation case the `Task.Delay` throwing an `OperationCanceledException` would not make the outer task `Cancelled` and thus bomb on shutting down
> Always delay moving of delayed messages even when exceptions occur to honor the ProcessingInterval

- GitVersion.yml
GitVersion bug workaround.
Similar to https://github.com/Particular/NServiceBus.RavenDB/pull/439
> Ignore the sha of the commit that promoted incorrect version

- src/NServiceBus.SqlServer/SubscriptionTableInstaller.cs
Core expects a task and does not handle a null response here.
> Fix Installer

- src/NServiceBus.SqlServer/SubscriptionTableInstaller.cs
Core expects a task and does not handle a null response here.
> Do not return null

- src/NServiceBus.SqlServer/Configuration/SettingsKeys.cs
- src/NServiceBus.SqlServer/Receiving/QueueCreator.cs
- src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
Delayed delivery needs to be disabled for some of the ServiceControl endpoints (such as staging queue processor and error ingestor)
> Allow disabling delayed delivery

- src/Scripts/Create-Databases.sql
- src/Scripts/Reset-Database.sql
Should fix the build problems when cleaning the database
```
following SET options have incorrect settings: 'QUOTED_IDENTIFIER'. Verify that SET options are correct for use with indexed views
```
apparently sqlcmd sets the [quoted identifiers to OFF](https://stackoverflow.com/questions/1137821/set-quoted-identifier-should-be-on-when-inserting-a-record) but the scripts need it ON for procedures and tables
> set quoted identifier on

- src/NServiceBus.Transport.SqlServer.TransportTests/ConfigureSqlServerTransportInfrastructure.cs
Looks like we overlooked this one when updating things for Microsoft.Data.SqlClient support.
> Use correct ifdef for project's target frameworks

- src/NServiceBus.SqlServer.IntegrationTests/When_message_receive_takes_long.cs
- src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
- src/NServiceBus.SqlServer/Queuing/TableBasedQueue.cs
- src/NServiceBus.SqlServer/Receiving/MessagePump.cs
Fixes #481
When peeking messages, we retrieve the count only up to the maximum concurrency level. This prevents the transport from effectively locking up if there are a lot of records to peek.
> Faster way to peek messages to retrieve message count (#480)

- src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs
- src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs
- src/NServiceBus.Transport.SqlServer/Receiving/SchemaVerification.cs
With the current index schema, there is a maximal throughput for a single queue and for the whole deployment that can't be increased by the scaling-up of the SQL server instance.  This is caused by the clustered index on the input queue that causes page latch contention on 
As a result, even a slight increase in message throughput can put a user in a position when scaling-up is not possible and other non-trivial actions e.g. transport infrastructure partitioning is required. 
This PR removes the clustered index, changing the input queue table to a heap and introduces a secondary non-clustered index based on the `RowVersion` column to enable the message receives based on that index.
Index creation script has been patched in the following versions of the transport:
* …
> Transport can't be scaled-up due to page latch contention

- src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
Since the AssemblyName is overridden in the project, it appears that default package id uses the assembly name instead of the project name like I thought.
This ensures that the correct package name is used.
> Fix package name

- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_receiving_messages.cs
- src/NServiceBus.Transport.SqlServer/Receiving/ExpiredMessagesPurger.cs
- src/NServiceBus.Transport.SqlServer/Receiving/IExpiredMessagesPurger.cs
- src/NServiceBus.Transport.SqlServer/Receiving/MessagePump.cs
- src/NServiceBus.Transport.SqlServer/Receiving/NoOpExpiredMessagesPurger.cs
- src/NServiceBus.Transport.SqlServer/Receiving/SchemaVerification.cs
- src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
Backport of #656 to `release-6.1` branch
* Introduce a NoOpPurger as well as clearer diagnostic sections
* no Index_Expires verification when expired message purging is off
* Cleanup unnecessary code
Co-authored-by: lailabougria <laila.bougria@particular.net>
Co-authored-by: Tomek Masternak <tomasz.masternak@particular.net>
> Introduce a NoOpPurger as well as clearer diagnostic sections

- src/NServiceBus.SqlServer.TransportTests/NServiceBus.SqlServer.TransportTests.csproj
- src/NServiceBus.Transport.SqlServer.TransportTests/NServiceBus.Transport.SqlServer.TransportTests.csproj
- src/NServiceBus.Transport.SqlServer.TransportTests/TransportTestLoggerFactory.cs
Can be reverted when https://github.com/Particular/NServiceBus/pull/5730 is merged and released
> TransportTests: Use a ConcurrentQueue for now to track log items

- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_checking_schema.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_dispatching_messages.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_message_receive_takes_long.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_receiving_messages.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_using_ttbr.cs
- src/NServiceBus.Transport.SqlServer.TransportTests/ConfigureSqlServerTransportInfrastructure.cs
- src/NServiceBus.Transport.SqlServer/Queuing/MessageRow.cs
- src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs
- src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueueCache.cs
- src/NServiceBus.Transport.SqlServer/SqlServerTransport.cs
- src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
I am not sure of the implications of this and would need someone more well versed in the history behind the need for sequential reads.
The reasons this is required are:
* When reading an encrypted column, `CommandBehavior.SequentialAccess` is not supported
* Without `CommandBehavior.SequentialAccess`, `SqlDataReader.GetStream` no longer works
This means that if we want to support having the headers and body columns and always encrypted columns, we need to stop using `CommandBehavior.SequentialAccess`.
Stopping the use of `CommandBehavior.SequentialAccess` means we have to stop using `GetStream`. Does typecasting to `byte[]` always work? I can't find references for when it would break down.
The PR only changes the code path when the `Column Encryption Setting` connection string parameter …
> Change read code to support Always Encrypted

- src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs
- src/NServiceBus.Transport.SqlServer/Receiving/SchemaVerification.cs
Closes #726
Cherry-pick of #725 for build automation to kick in
SchemaVerification currently just searches for indexes on the queue table named Index_Expires and Index_RowVersion (the latter with a specific type).
Our deployment scripts create the correct indexes, but they are named differently. This gives false warnings on startup.
In this PR I have created queries that instead looks for an index, that have the specified column as its first element (key_ordinal=1), and for RowVersion still also checkes for non-clustered type. Apart from solving our own problem, it also solves the issue, that startup currently will not warn, if eg. Index_Expires exists but is designed wrongly.
> Better SchemaVerification index search

- src/NServiceBus.Transport.SqlServer/Receiving/RepeatedFailuresOverTimeCircuitBreaker.cs
Verified that all 4 usages of this method from within catch blocks either deal with the OCE immediately or do up the chain.
> Delay of up to 10s should use passed cancellation token

- src/NServiceBus.Transport.SqlServer/Queuing/SqlCommandExtensions.cs
- src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs
@kbaley @DavidBoike @kentdr this is a more generalised version of https://github.com/Particular/NServiceBus.SqlServer/pull/846 which also takes into account the recommendation to log warnings by @tmasternak and also covers the remaining calls to `ExecuteScalarAsync` as mentioned by @ramonsmits [here](https://github.com/Particular/NServiceBus.SqlServer/pull/847/files#r647179404) and [here](https://github.com/Particular/NServiceBus.SqlServer/pull/847/files#r647180005).
fixes https://github.com/Particular/NServiceBus.SqlServer/issues/848
> defend against ExecuteScalarAsync returning unexpected values

- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_receiving_messages.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_recoverable_column_is_removed.cs
- src/NServiceBus.Transport.SqlServer/Queuing/Message.cs
- src/NServiceBus.Transport.SqlServer/Queuing/MessageRow.cs
- src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs
- src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs
* Stops using CorrelationId/ReplyToAddress columns except in table creation
* Determines if each table contains a Recoverable column and adjusts Send command to match
Couldn't be removed until a later major, once all endpoints were running the major containing this PR.
> Phase 1 of removing Recoverable/CorrelationId/ReplyToAddress columns

- README.md
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/ConfigureEndpointSqlServerTransport.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiCatalog/MultiCatalogAcceptanceTest.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiSchema/When_custom_schema_configured_for_legacy_publisher.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativePubSub/When_migrating_publisher_first.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativePubSub/When_migrating_subscriber_first.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativePubSub/When_publisher_runs_in_compat_mode.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativePubSub/When_subscriber_runs_in_compat_mode.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/TimeToBeReceived/When_queue_contains_expired_messages.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_a_corrupted_message_is_received.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_passing_custom_connection_in_receive_context.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_passing_custom_connection_outside_receive_context.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_passing_custom_transaction_in_receive_context.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_passing_custom_transaction_outside_receive_context.cs
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_using_custom_connection_factory.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_checking_schema.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_dispatching_messages.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_message_receive_takes_long.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_receiving_messages.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_recoverable_column_is_removed.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_using_ttbr.cs
- src/NServiceBus.Transport.SqlServer.TransportTests/ConfigureSqlServerTransportInfrastructure.cs
Similar to https://github.com/Particular/NServiceBus.RabbitMQ/pull/839
Another WTF here is that the reading of the env var is spread across so many places, but I didn't want to tackle that here.
> ensure and align default connection string for tests

- src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativeTimeouts/When_deferring_a_message_to_invalid_queue.cs
- src/NServiceBus.Transport.SqlServer/ExceptionExtensions.cs
- src/NServiceBus.Transport.SqlServer/Receiving/ExceptionHeaderHelper.cs
- src/NServiceBus.Transport.SqlServer/Receiving/ProcessStrategy.cs
by moving them to the error queue with all the exception headers set and the FailedQ header pointing to the (invalid) destination queue
> Handle delayed message with invalid destination

- src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_using_column_encrypted_connection.cs
- src/NServiceBus.Transport.SqlServer/NServiceBus.Transport.SqlServer.csproj
- src/NServiceBus.Transport.SqlServer/Queuing/MessageRow.cs
Backport of https://github.com/Particular/NServiceBus.SqlServer/pull/1179 which fixes https://github.com/Particular/NServiceBus.SqlServer/issues/1150 for the `release-7.0` branch
> IndexOutOfRangeException is thrown when using version 7.0.0 and Always Encrypted Columns

- src/NServiceBus.Transport.SqlServer/NServiceBus.Transport.SqlServer.csproj
Looks like [Microsoft.Data.SqlClient 5.1.4 includes the DTC deadlock fix](https://github.com/dotnet/SqlClient/releases/tag/v5.1.4), so we no longer need to reference the 5.2 preview.
> Update Microsoft.Data.SqlClient to 5.1.4

- .github/workflows/ci.yml
- .github/workflows/release.yml
- src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
- src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
- src/NServiceBus.SqlServer.TransportTests/NServiceBus.SqlServer.TransportTests.csproj
- src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
- src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/NServiceBus.Transport.SqlServer.AcceptanceTests.csproj
- src/NServiceBus.Transport.SqlServer.IntegrationTests/NServiceBus.Transport.SqlServer.IntegrationTests.csproj
- src/NServiceBus.Transport.SqlServer.TransportTests/NServiceBus.Transport.SqlServer.TransportTests.csproj
- src/NServiceBus.Transport.SqlServer.UnitTests/NServiceBus.Transport.SqlServer.UnitTests.csproj
- src/NServiceBus.Transport.SqlServer/NServiceBus.Transport.SqlServer.csproj
Updates vulnerable SQL Client dependency to patched versions:
* [CVE-2022-41064](https://github.com/advisories/GHSA-8g2p-5pqh-5jmc)
* [CVE-2024-0056](https://github.com/advisories/GHSA-98g6-xh36-x2p7)
While it is possible for an end-user to update to the patched versions without updating the NServiceBus component, this change sets the known patched versions as the minimum allowable version.
> Version 6.3.4 uses vulnerable versions of SQL Client dependency

- src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs
- Related to #863 
Backports:
- #1292 
- #1278
The updated peek query will ignore rows
- for messages that are currently being inserted within an uncommitted transaction
- currently being locked by, for example, another competing consumer
This can happen when a sender sends a large batch of messages. The query that calculates how many "messages" are available to be fetched previously would read uncommitted data and continuously fire queries to fetch new messages but not receive any new data because the data was not yet committed.
The hint `READCOMMITTEDLOCK`is required when the database has snapshot isolation enabled, which is the default in SQL Azure instances. Previously any consumer would DELETE. Because the peek used `NOLOCK` the result would exclude the deleted rows. However, with …
> READPAST,READCOMMITTEDLOCK instead of NOLOCK to not read uncommitted data

- src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs
- Backport of #1277 for release branch `release-7.0` to be released in version 7.0.5
> READPAST,READCOMMITTEDLOCK instead of NOLOCK to not read uncommitted data - 7.0

- src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs
- Backport of https://github.com/Particular/NServiceBus.SqlServer/pull/1277 for release branch `release-6.3` to be released in version 6.3.7
> READPAST,READCOMMITTEDLOCK instead of NOLOCK to not read uncommitted data - 6.3

- src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
to make sure clients start upgrading to later versions without enforcing them to have Encrypt=true that was introduced in a breaking change in 4.x of the client
> Log warn when the Microsoft.Data.SqlClient version is below 5.2.0

- src/NServiceBus.Transport.PostgreSql.UnitTests/NServiceBus.Transport.PostgreSql.UnitTests.csproj
- src/NServiceBus.Transport.Sql.Shared/NServiceBus.Transport.Sql.Shared.csproj
- src/NServiceBus.Transport.SqlServer.IntegrationTests/NServiceBus.Transport.SqlServer.IntegrationTests.csproj
- src/NServiceBus.Transport.SqlServer.UnitTests/NServiceBus.Transport.SqlServer.UnitTests.csproj
This ensures we run with [the latest version of TTBR acceptance tests](https://github.com/Particular/NServiceBus/pull/7062)
> Update to NServiceBus version 9.0.2

- src/NServiceBus.Transport.Sql.Shared/DelayedDelivery/BackOffStrategy.cs
- src/NServiceBus.Transport.SqlServer.UnitTests/DelayedDelivery/BackOffStrategyTests.cs
- src/NServiceBus.Transport.SqlServer.UnitTests/NServiceBus.Transport.SqlServer.UnitTests.csproj
Copied from #1383
> I stumbled upon a strange behavior regarding NSB and delayed messaged on SQL transport.
> Sometimes delayed messages would not be processed anymore, without any exception or anything being logged. They just stay in the .Delayed table and are not moved to their target table anymore.
> If they are moved there manually, the messages are processed normally.
> 
> In the logs I found occurrences of the following error: "The value needs to be either -1 (signifying an infinite timeout), 0 or a positive integer." in BackOffStrategy.WaitForNextExecution.
> This shows, that sometimes negative values can be calculated. And in case of a -1, it would lead to an infinite wait time, which could explain my noticed behavior.
> 
> Unfortunately I was not able to write a stable test to …
> Fix SQL delayed delivery polling 

- src/NServiceBus.Transport.PostgreSql.TransportTests/ConfigurePostgreSqlTransportInfrastructure.cs
- src/NServiceBus.Transport.PostgreSql.TransportTests/NServiceBus.Transport.PostgreSql.TransportTests.csproj
- src/NServiceBus.Transport.PostgreSql.TransportTests/When_receive_takes_long_to_complete.cs
- src/NServiceBus.Transport.PostgreSql/PostgreSqlConstants.cs
- src/NServiceBus.Transport.Sql.Shared/NServiceBus.Transport.Sql.Shared.csproj
- src/NServiceBus.Transport.SqlServer.TransportTests/ConfigureSqlServerTransportInfrastructure.cs
- src/NServiceBus.Transport.SqlServer.TransportTests/NServiceBus.Transport.SqlServer.TransportTests.csproj
- src/NServiceBus.Transport.SqlServer.TransportTests/When_receive_takes_long_to_complete.cs
Backport of #1443  which fixes #1412 for the `release-8.1` branch
> High CPU utilization due to large number of DELETE statements

- src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativeTimeouts/When_configured_to_purge_expired_messages_at_startup.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_checking_schema.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_dispatching_messages.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_message_receive_takes_long.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_receiving_messages.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_recoverable_column_is_removed.cs
- src/NServiceBus.Transport.SqlServer.IntegrationTests/When_using_ttbr.cs
- src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs
- src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs
- src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueueCache.cs
- src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
Backport of #1442 which fixes #1196  for the `release-7.0` branch
> SQL Server transport requires SELECT permission when sending to remote queues

- .github/workflows/ci.yml
- src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiCatalog/When_catalog_with_special_characters_configured_for_endpoint.cs
- src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs
> Quote the catalog name when preparing the send command text in SQL Server

- src/NServiceBus.Transport.PostgreSql/PostgreSqlTransportInfrastructure.cs
- src/NServiceBus.Transport.PostgreSql/Receiving/QueueCreator.cs
- src/NServiceBus.Transport.Sql.Shared/Receiving/MessageReceiver.cs
- src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
This aligns the transport to stop the pumps on transport shutdown and at the same time makes sure the pumps stop method can be called multiple times. 
This is part of addressing some low-hanging fruit to align all transports for the transport seam usage scenarios to make sure pumps are stopped when the transport shuts down. 
I have tried to write a transport test for it to enforce it eventually for all transport but couldn't find a way to do that without introducing flags on the transport interface and using fancy techniques like default members which seams overkill
> Stop pumps on shutdown

- src/NServiceBus.Transport.Sql.Shared/Receiving/MessageReceiver.cs
Resolves that the lock object introduced in the following PR isn't static and no longer public:
- https://github.com/Particular/NServiceBus.SqlServer/pull/1534
Approvals didn't need updating because the class itself is private.
> Make receiver concurrency lock object private and non static

- src/NServiceBus.Transport.PostgreSql/PostgreSqlTransportInfrastructure.cs
- src/NServiceBus.Transport.Sql.Shared/PubSub/CachedSubscriptionStore.cs
- src/NServiceBus.Transport.SqlServer.UnitTests/CachedSubscriptionStoreTests.cs
- src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
Fixes #1588 
- Fixed cancellation coupling: Previously cached Task<List> could carry a caller’s CancellationToken, causing unintended cancellations for later callers. Now the cache stores the result so each caller’s token is handled independently during fetch.
- Preserved cache behavior: Expiration and invalidation on Subscribe/Unsubscribe are unchanged.
- Thundering herd mitigation: A SemaphoreSlim serializes refreshes so only one fetch occurs per event type when the cache is empty/expired, reducing concurrent connections and avoiding pool exhaustion.
- Deterministic invalidation: Clear runs without flowing caller cancellation to ensure cache is always invalidated after updates.
- Stable timing: Cache freshness uses Stopwatch-based elapsed time, avoiding issues from system clock …
> Avoid cancellation token cross-contamination and thundering herd in subscription cache
