Particular/NServiceBus.SqlServer

packaging/nuget/NServiceBus.SqlServer.nuspec
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.SqlServer/SqlServerMessageSender.cs
src/NServiceBus.SqlServer/SqlServerTransport.cs
src/NServiceBus.SqlServer/packages.config

related to https://github.com/Particular/NServiceBus/issues/2885 , message senders need a way to send a message without enlisting in native transactions.
also fixes https://github.com/Particular/NServiceBus.SqlServer/issues/91

support suppressing native transactions

---

src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.SqlServer.AcceptanceTests/When_using_custom_connection_factory.cs
src/NServiceBus.SqlServer/MessagePump.cs
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.SqlServer/ReceiveWithNativeTransaction.cs
src/NServiceBus.SqlServer/ReceiveWithNoTransaction.cs
src/NServiceBus.SqlServer/ReceiveWithTransactionScope.cs
src/NServiceBus.SqlServer/SqlConnectionFactory.cs
src/NServiceBus.SqlServer/SqlServerMessageDispatcher.cs
src/NServiceBus.SqlServer/SqlServerQueueCreator.cs
src/NServiceBus.SqlServer/SqlServerSettingsKeys.cs
src/NServiceBus.SqlServer/SqlServerTransport.cs
src/NServiceBus.SqlServer/SqlServerTransportSettingsExtensions.cs
src/NServiceBus.SqlServer/obsoletes.cs

Part of #100 
Reason we need this: https://github.com/Particular/NServiceBus.SqlServer/pull/86
Waiting for: https://github.com/Particular/NServiceBus/pull/3158

Support for custom sql connection factory

---

src/NServiceBus.SqlServer.AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1328/Sagas/When_forgetting_to_set_a_corr_property.cs
src/NServiceBus.SqlServer.AcceptanceTests/Configuration/When_using_v2_configuration_app_config_for_schema_override.cs
src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.SqlServer.AcceptanceTests/packages.config
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.SqlServer/Receiving/MessagePump.cs
src/NServiceBus.SqlServer/Receiving/ReceiveStrategy.cs
src/NServiceBus.SqlServer/Receiving/ReceiveWithNoTransaction.cs
src/NServiceBus.SqlServer/Receiving/ReceiveWithReceiveOnlyTransaction.cs
src/NServiceBus.SqlServer/Receiving/ReceiveWithSendsAtomicWithReceiveTransaction.cs
src/NServiceBus.SqlServer/Receiving/ReceiveWithTransactionScope.cs
src/NServiceBus.SqlServer/SqlServerTransport.cs
src/NServiceBus.SqlServer/packages.config

Abort using cancellationtoken

---

src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.SqlServer/Queuing/DictionarySerializer.cs
src/NServiceBus.SqlServer/Queuing/MessageParser.cs

replaces https://github.com/Particular/NServiceBus.SqlServer/pull/152

use DataContractJsonSerializer for headers

---

src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.SqlServer/packages.config

Part of https://github.com/Particular/PlatformDevelopment/issues/610

Added coderules

---

src/NServiceBus.SqlServer/TableBasedQueue.cs

Replace IIF function with CASE statement in TTBR calculations to support SQL Server 2008.
Resolves #182.

Hotfix 2.2.3

---

src/NServiceBus.SqlServer/Queuing/Sql.cs

Replace IIF with CASE to support SQL Server 2008

---

src/NServiceBus.SqlServer/SqlServerTransport.cs

fixes https://github.com/Particular/NServiceBus/issues/3635

remove RequiresConnectionString

---

src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj.DotSettings

Connects to: #139 
@SimonCropp

removing C# 5 language check

---

src/NServiceBus.SqlServer/obsoletes.cs

Connects to https://github.com/Particular/NServiceBus.SqlServer/issues/139.
To use "multi-instance" instead of "multi-database".

Update messages on obsoleted methods

---

src/NServiceBus.SqlServer/Receiving/MessagePump.cs

Connects to https://github.com/Particular/NServiceBus.SqlServer/issues/181
I reviewed the current message pump and couldn't figure out why we are enforcing a thread with `Task.Run` and scheduling another task to dispose the `CancellationTokenSource`. In my opinion the receive strategy and the whole call stack inside is truly asynchronous by leveraging the asynchronous APIs of `SqlConnection`, `DatabaseCommand` and so forth. So enforcing to run the receive strategy on a dedicated thread doesn' t make sense for me.
@Particular/transport-maintainers please review

InnerReceive is assumed to be truly async and schedules less tasks

---

src/NServiceBus.SqlServer/Sending/MessageDispatcher.cs

Connects to https://github.com/Particular/EndToEnd/issues/3
Relates to #181 
In order to understand the implications of #181 I needed to dig deeper into the Sql Transport code. While doing this I realized we are using unnecessary connections inside the same batch. This PR reuses the existing code but does the following:
It creates two paths. One for `Isolated` dispatch consistency and one for `default` consistency.
Side note: The core has a small design flaw. We are marking all operations in a batch as `Isolated` when the outbox is used. Under the outbox we would actually not required any transaction scope. The only thing we would need to make sure is that we are not participating in the receive transaction. But since the core API doesn't allow to differentiate between immediate dispatch …

MessageDispatcher sorts batch per dispatch consistency and reuses the connections more efficiently

---

src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacyMessageDispatcher.cs
src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacySqlServerTransportInfrastructure.cs
src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacyTableBasedQueueDispatcher.cs
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj

Connects to #181 
@SzymonPobiega apparently we completely forgot this case. Can you help me smoke test it and review?
@Particular/sqlserver-transport-maintainers please review

Deduplicating in the legacy dispatcher as well.

---

src/NServiceBus.SqlServer/FodyWeavers.xml
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.SqlServer/packages.config

Connects to Particular/PlatformDevelopment#732.

Update Janitor.Fody to 1.2.0

---

src/NServiceBus.SqlServer.AcceptanceTests/When_a_corrupted_message_is_received.cs

Connects to https://github.com/Particular/PlatformDevelopment/issues/732
@tmasternak please review.

Added 'IF EXISTS' to the purge.

---

src/NServiceBus.SqlServer.AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-beta0002/Recoverability/Retries/When_performing_slr_with_flr_disabled.cs
src/NServiceBus.SqlServer.AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-beta0002/Sagas/When_auto_correlated_property_is_changed.cs
src/NServiceBus.SqlServer.AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-beta0002/Sagas/When_updating_existing_correlation_property.cs

Connects to https://github.com/Particular/PlatformDevelopment/issues/732
/cc: @SzymonPobiega

Fixing flaky att

---

src/NServiceBus.SqlServer/Sending/TableBasedQueueDispatcher.cs

While doing performance testing we found out that sends are still a magnitude slower compared to previous versions. The effect becomes more apparent the more latency is involved between the client and the sql server.
The main reason is that we ALWAYS wrap even single insert statements in a SQL transaction when doing non-isolated dispatches. This is not necessary. For more information see
http://stackoverflow.com/questions/1171749/what-does-a-transaction-around-a-single-statement-do
> Send: NumberOfMessages 10000, MessageSize 1024, Concurrency 1, TimeInMs 11771
> Send: NumberOfMessages 10000, MessageSize 4096, Concurrency 1, TimeInMs 12260
> Send: NumberOfMessages 10000, MessageSize 16384, Concurrency 1, TimeInMs 12276
> Send: NumberOfMessages 10000, MessageSize 65536, Concurrency 1, …

Avoid transaction creation for send operations with only non-isolated operation to dispatch

---

src/NServiceBus.SqlServer.AcceptanceTests/Configuration/When_using_v2_configuration_app_config_for_schema_override.cs

ping @Particular/sqlserver-transport-maintainers. This is making release branch ATT fail. Turns out the setup of custom app.config was using invalid path.

Fixed failing configuration validation test

---

src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
src/NServiceBus.SqlServer.IntegrationTests/When_message_receive_takes_long.cs
src/NServiceBus.SqlServer.IntegrationTests/When_receiving_messages.cs
src/NServiceBus.SqlServer/Queuing/Sql.cs
src/NServiceBus.SqlServer/Queuing/TableBasedQueue.cs

QueuePeeker does select with READPAST hint

---

src/NServiceBus.SqlServer.IntegrationTests/When_dispatching_messages.cs
src/NServiceBus.SqlServer/Queuing/TableBasedQueue.cs

Handling missing table by throwing QueueNotFoundException

---

src/NServiceBus.SqlServer/Receiving/MessagePump.cs

* Grammar and magic number
* Term 'table' renamed to 'queue' in logging
This is a cherry-pick to release branch.

Grammar and magic number (#254)

---

src/NServiceBus.SqlServer.AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-beta0003/Sagas/When_saga_id_changed.cs
src/NServiceBus.SqlServer.AcceptanceTests/ConfigureEndpointSqlServerTransport.cs

Also, fix failing saga identifier change acceptance test.

Fix cleanup of queue tables after the test

---

src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacyQueuePeeker.cs
src/NServiceBus.SqlServer/Receiving/QueuePeeker.cs

logging info message when delaying peek operation

---

src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacyQueuePeeker.cs
src/NServiceBus.SqlServer/Receiving/QueuePeeker.cs

Log queue peeker delay on debug level

---

src/NServiceBus.SqlServer.IntegrationTests/When_receiving_messages.cs
src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacyReceiveWithTransactionScope.cs
src/NServiceBus.SqlServer/Queuing/Message.cs
src/NServiceBus.SqlServer/Queuing/MessageRow.cs
src/NServiceBus.SqlServer/Receiving/ReceiveStrategy.cs
src/NServiceBus.SqlServer/Receiving/ReceiveWithNativeTransaction.cs
src/NServiceBus.SqlServer/Receiving/ReceiveWithNoTransaction.cs
src/NServiceBus.SqlServer/Receiving/ReceiveWithTransactionScope.cs

See https://github.com/Particular/NServiceBus/pull/3956
Does not address all other release branch changes from core

Using byte array instead of stream

---

src/NServiceBus.SqlServer.UnitTests/APIApprovals.Approve.approved.txt
src/NServiceBus.SqlServer/SqlServerTransport.cs

Related to https://github.com/Particular/NServiceBus/pull/3816

Added IMessageDrivenSubscriptionTransport marker interface to transport def

---

src/NServiceBus.SqlServer.IntegrationTests/When_receiving_messages.cs
src/NServiceBus.SqlServer.UnitTests/APIApprovals.Approve.approved.txt
src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacyQueuePeeker.cs
src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacySqlServerTransportInfrastructure.cs
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.SqlServer/Receiving/QueuePeeker.cs
src/NServiceBus.SqlServer/Receiving/QueuePeekerOptions.cs
src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
src/NServiceBus.SqlServer/SqlServerTransportSettingsExtensions.cs

This one replaces #292 and should address all the previous comments.  The documentation will be done as a part of Particular/docs.particular.net#1835

Added settings for queue peeker delay

---

src/NServiceBus.SqlServer.UnitTests/ConnectionPoolValidatorTests.cs
src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
src/NServiceBus.SqlServer/Configuration/ConnectionPoolValidator.cs
src/NServiceBus.SqlServer/Configuration/SqlConnectionFactory.cs
src/NServiceBus.SqlServer/Configuration/ValidationCheckResult.cs
src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacySqlConnectionFactory.cs
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs

This will check connection pool settings on the provided connection string for send and receive infrastructures.

Added connection pool validation. Related to #204.

---

src/NServiceBus.SqlServer.AcceptanceTests/LegacyMultiInstance/When_using_legacy_multiinstance.cs
src/NServiceBus.SqlServer.UnitTests/APIApprovals.Approve.approved.txt
src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacySqlConnectionFactory.cs
src/NServiceBus.SqlServer/SqlServerTransportSettingsExtensions.cs

Connects to: https://github.com/Particular/NServiceBus.SqlServer/issues/264

Legacy multi instance factory method changes

---

src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacyQueuePeeker.cs
src/NServiceBus.SqlServer/Receiving/MessagePump.cs
src/NServiceBus.SqlServer/Receiving/QueuePeeker.cs

Fixes #299 
See https://github.com/Particular/NServiceBus.SqlServer/issues/299#issuecomment-248846384 for details

Catch and log sql exception when task cancellation requested

---

src/NServiceBus.SqlServer/Receiving/ExpiredMessagesPurger.cs
src/NServiceBus.SqlServer/Receiving/MessagePump.cs

Temporary fix for #308 
/cc: @Particular/sqlserver-transport-maintainers

Preventing deadlock exceptions from shutindown the endpoint

---

src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacyQueuePeeker.cs
src/NServiceBus.SqlServer/Receiving/QueuePeeker.cs

enforcing transaction isolation level on peeks

---

src/NServiceBus.SqlServer/Configuration/ConnectionStringsValidator.cs

Point to upgrade guide instead of irrelevant doco
Resolves #322

Fix terminology in error message

---

src/NServiceBus.SqlServer.AcceptanceTests/ConfigureEndpointSqlServerTransport.cs
src/NServiceBus.SqlServer.AcceptanceTests/MultiSchema/When_custom_schema_contains_at.cs
src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.SqlServer.AcceptanceTests/QueueAddress.cs
src/NServiceBus.SqlServer.AcceptanceTests/When_using_brackets_around_endpoint_names.cs
src/NServiceBus.SqlServer.AcceptanceTests/When_using_special_characters_in_endpoint_name.cs
src/NServiceBus.SqlServer.UnitTests/QueueAddressTests.cs
src/NServiceBus.SqlServer/Addressing/QueueAddress.cs
src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacyQueueCreator.cs
src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
src/NServiceBus.SqlServer/Receiving/QueueCreator.cs
src/Scripts/Reset-Database.sql

* Brackets inside endpoint name e.g. `var cfg = new EndpointConfiguration("My]Endpoint")`
* Brackets around endpoint name e.g. `var cfg = new EndpointConfiguration("[MyEndpoint]")`

Handling of special characters

---

src/CompatibilityTests/Facade_2.2/EndpointFacade.cs
src/NServiceBus.SqlServer.sln.DotSettings
src/NServiceBus.SqlServer/Configuration/SqlConnectionFactory.cs
src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacyMessageDispatcher.cs
src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
src/NServiceBus.SqlServer/Receiving/MessagePump.cs
src/NServiceBus.SqlServer/Sending/MessageDispatcher.cs
src/NServiceBus.SqlServer/Sending/TableBasedQueueDispatcher.cs
src/NServiceBus.SqlServer/SqlServerTransportSettingsExtensions.cs

That i noticed while checking how something worked

Some minor cleanups

---

src/NServiceBus.SqlServer/Queuing/SqlConstants.cs

Index_Expires should be filtered

---

src/NServiceBus.SqlServer/Addressing/CanonicalQueueAddress.cs
src/NServiceBus.SqlServer/DelayedDelivery/DelayedDeliveryQueueCreator.cs
src/NServiceBus.SqlServer/Receiving/QueueCreator.cs

Quote catalog name in DDL statements

---

src/NServiceBus.SqlServer.AcceptanceTests/LegacyMultiInstance/When_doing_request_reply_between_modes.cs
src/NServiceBus.SqlServer.AcceptanceTests/LegacyMultiInstance/When_using_legacy_multiinstance.cs
src/NServiceBus.SqlServer.AcceptanceTests/MultiCatalog/MultiCatalogAcceptanceTest.cs
src/NServiceBus.SqlServer.AcceptanceTests/MultiCatalog/When_configured_error_queue_includes_catalog.cs
src/NServiceBus.SqlServer.AcceptanceTests/MultiCatalog/When_custom_catalog_configured_for_endpoint.cs
src/NServiceBus.SqlServer.AcceptanceTests/MultiCatalog/When_custom_catalog_configured_for_error_queue.cs
src/NServiceBus.SqlServer.AcceptanceTests/TimeToBeReceived/When_queue_contains_expired_messages.cs
src/NServiceBus.SqlServer.AcceptanceTests/When_a_corrupted_message_is_received.cs
src/NServiceBus.SqlServer.AcceptanceTests/When_using_custom_connection_factory.cs
src/NServiceBus.SqlServer.CompatibilityTests/ConnectionStrings.cs
src/NServiceBus.SqlServer.IntegrationTests.NHibernate/When_using_transaction_scope.cs
src/NServiceBus.SqlServer.IntegrationTests.Sql/When_using_transaction_scope.cs
src/NServiceBus.SqlServer.IntegrationTests/SqlServerTransportTests.cs
src/NServiceBus.SqlServer.IntegrationTests/When_checking_schema.cs
src/NServiceBus.SqlServer.IntegrationTests/When_dispatching_messages.cs
src/NServiceBus.SqlServer.IntegrationTests/When_message_receive_takes_long.cs
src/NServiceBus.SqlServer.IntegrationTests/When_receiving_messages.cs
src/NServiceBus.SqlServer.IntegrationTests/When_using_ttbr.cs
src/NServiceBus.SqlServer.TransportTests/ConfigureSqlServerTransportInfrastructure.cs

Read connection strings from env variables

---

src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj

Do not expose GitVersionTask as a dependency

---

src/NServiceBus.SqlServer/DelayedDelivery/DelayedDeliveryMessagePump.cs
src/NServiceBus.SqlServer/DelayedDelivery/DelayedMessageProcessor.cs
src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs

In order to be able to run SQL Server transport in NSB.Raw

Replaces the usages of Settings.LocalAddress and Settings.LogicalAddress

---

GitVersion.yml
src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.SqlServer.CompatibilityTests/NServiceBus.SqlServer.CompatibilityTests.csproj
src/NServiceBus.SqlServer.IntegrationTests.Sql/NServiceBus.SqlServer.IntegrationTests.Sql.csproj
src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
src/NServiceBus.SqlServer.TransportTests/NServiceBus.SqlServer.TransportTests.csproj
src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
src/NServiceBus.SqlServer.sln
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj

@Particular/sqlserver-transport-maintainers Please review and merge!

Prepare for final beta release

---

src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs

This ensures that the transport will fail on startup if the `TransactionScope` transport transaction mode has been selected when running against versions of the System.Data.SqlClient package that don't support ambient transaction enlistment.
The first version of the package that will support this is the 4.5.0 release, which is part of .NET Core 2.1.
FYI @timbussmann @andreasohlund @tmasternak

Add startup check for ambient transaction enlistment support

---

src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
src/Scripts/Create-Databases.sql
src/Scripts/Reset-Database.sql

makes it easier to debug when looking at the raw sql tables

add computed column to convert body to nvarchar

---

src/NServiceBus.SqlServer/Queuing/MessageRow.cs
src/NServiceBus.SqlServer/Queuing/SqlConstants.cs

no need to read it or represent it in .net

remove some Recoverable noise

---

src/NServiceBus.SqlServer.UnitTests/APIApprovals.Approve.approved.txt
src/NServiceBus.SqlServer/Queuing/SqlConstants.cs

so it can be consumed for scripting purposes

make CreateDelayedMessageStoreText public

---

src/NServiceBus.SqlServer.AcceptanceTests/When_using_computed_message_body_column.cs
src/NServiceBus.SqlServer.UnitTests/APIApprovals.Approve.approved.txt
src/NServiceBus.SqlServer/Configuration/SettingsKeys.cs
src/NServiceBus.SqlServer/DelayedDelivery/DelayedDeliveryQueueCreator.cs
src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
src/NServiceBus.SqlServer/Receiving/QueueCreator.cs
src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
src/NServiceBus.SqlServer/SqlServerTransportSettingsExtensions.cs
src/Scripts/Create-Databases.sql
src/Scripts/Reset-Database.sql

Fixes https://github.com/Particular/NServiceBus.SqlServer/issues/445

Message body computed column

---

src/NServiceBus.SqlServer/SqlServerTransportSettingsExtensions.cs

Fixes https://github.com/Particular/NServiceBus.SqlServer/issues/312

add a warning

---

src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs
src/NServiceBus.SqlServer/SqlServerTransportSettingsExtensions.cs

Fixes https://github.com/Particular/NServiceBus.SqlServer/issues/404

Diagnostics info

---

src/NServiceBus.SqlServer/Receiving/MessagePump.cs

Fix inspections

---

src/NServiceBus.SqlServer/DelayedDelivery/DelayedMessageHandler.cs
src/NServiceBus.SqlServer/DelayedDelivery/DelayedMessageTable.cs
src/NServiceBus.SqlServer/DelayedDelivery/StoreDelayedMessageCommand.cs
src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
src/NServiceBus.SqlServer/TaskEx.cs

Merge master into release

---

src/NServiceBus.SqlServer/DelayedDelivery/DelayedMessageHandler.cs
src/NServiceBus.SqlServer/DelayedDelivery/DelayedMessageTable.cs
src/NServiceBus.SqlServer/TaskEx.cs

 Always delay moving of delayed messages even when exceptions occur to honor the ProcessingInterval

---

src/NServiceBus.SqlServer/Receiving/MessagePump.cs

as discussed with @mikeminutillo

decimal points make no sense in message counts

---

GitVersion.yml
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj

Update Particular.Packaging in master

---

GitVersion.yml
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj

Update Particular.Packaging in release-3.1

---

GitVersion.yml
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj

Update Particular.Packaging in release-5.0

---

GitVersion.yml
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj

Update Particular.Packaging in release-4.1

---

GitVersion.yml
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj

Update Particular.Packaging in release-4.3

---

src/NServiceBus.SqlServer.UnitTests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiCatalog/When_custom_catalog_configured_for_endpoint.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiCatalog/When_custom_catalog_configured_for_error_queue.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiCatalog/When_custom_catalog_configured_for_legacy_publisher.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiCatalog/When_custom_catalog_configured_for_publisher_and_subscriber.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiSchema/When_custom_schema_configured_for_endpoint.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiSchema/When_custom_schema_configured_for_endpoint_with_brackets_syntax.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiSchema/When_custom_schema_configured_for_endpoint_with_default_override.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiSchema/When_custom_schema_configured_for_endpoint_with_queue_specific_override.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiSchema/When_custom_schema_configured_for_error_queue.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiSchema/When_custom_schema_configured_for_legacy_publisher.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiSchema/When_custom_schema_configured_for_publisher_and_subscriber.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiSchema/When_custom_schema_contains_at.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativePubSub/When_publisher_runs_in_compat_mode.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativePubSub/When_subscriber_runs_in_compat_mode.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativeTimeouts/When_deferring_a_message_in_timeout_manager_compatibility_mode.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/TransactionScope/When_customizing_scope_isolation_level.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/TransactionScope/When_using_scope_timeout_greater_than_machine_max.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_passing_custom_transaction_via_sendoptions.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_using_computed_message_body_column.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_using_custom_connection_factory.cs
src/NServiceBus.Transport.SqlServer.UnitTests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Transport.SqlServer/PubSub/MessageDrivenPubSubCompatibilityModeConfiguration.cs
src/NServiceBus.Transport.SqlServer/SendOptionsExtensions.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransportSettingsExtensions.cs

This aligns these settings classes with our namespace rules.

Move settings into NServiceBus namespace

---

src/NServiceBus.SqlServer.CompatibilityTests/NServiceBus.SqlServer.CompatibilityTests.csproj
src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
src/NServiceBus.Transport.SqlServer.IntegrationTests/NServiceBus.Transport.SqlServer.IntegrationTests.csproj
src/NServiceBus.Transport.SqlServer.UnitTests/NServiceBus.Transport.SqlServer.UnitTests.csproj

Update relevant projects to latest NServiceBus Core patch

---

src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
src/NServiceBus.SqlServer.TransportTests/NServiceBus.SqlServer.TransportTests.csproj
src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj

Update test projects to netcoreapp3.1 in release-5.0

---

src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
src/NServiceBus.SqlServer.TransportTests/NServiceBus.SqlServer.TransportTests.csproj
src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj

Update test projects to netcoreapp3.1 in release-4.1

---

src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
src/NServiceBus.SqlServer.TransportTests/NServiceBus.SqlServer.TransportTests.csproj
src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
src/NServiceBus.Transport.SqlServer.AcceptanceTests/NServiceBus.Transport.SqlServer.AcceptanceTests.csproj
src/NServiceBus.Transport.SqlServer.IntegrationTests/NServiceBus.Transport.SqlServer.IntegrationTests.csproj
src/NServiceBus.Transport.SqlServer.TransportTests/NServiceBus.Transport.SqlServer.TransportTests.csproj
src/NServiceBus.Transport.SqlServer.UnitTests/NServiceBus.Transport.SqlServer.UnitTests.csproj

Update test projects to netcoreapp3.1 in master

---

src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
src/NServiceBus.SqlServer.TransportTests/NServiceBus.SqlServer.TransportTests.csproj
src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
src/NServiceBus.Transport.SqlServer.AcceptanceTests/NServiceBus.Transport.SqlServer.AcceptanceTests.csproj
src/NServiceBus.Transport.SqlServer.IntegrationTests/NServiceBus.Transport.SqlServer.IntegrationTests.csproj
src/NServiceBus.Transport.SqlServer.TransportTests/NServiceBus.Transport.SqlServer.TransportTests.csproj
src/NServiceBus.Transport.SqlServer.UnitTests/NServiceBus.Transport.SqlServer.UnitTests.csproj
src/NServiceBus.Transport.SqlServer/Receiving/QueueCreator.cs

Update test projects to netcoreapp3.1 in release-6.0

---

src/NServiceBus.Transport.SqlServer.TransportTests/ConfigureSqlServerTransportInfrastructure.cs

Port of #581 for `release-6.0`.

Use correct ifdef for project's target frameworks

---

src/NServiceBus.SqlServer.CompatibilityTests/NServiceBus.SqlServer.CompatibilityTests.csproj

Update test projects to NServiceBus 7.2.3 in release-6.0

---

src/NServiceBus.SqlServer.CompatibilityTests/NServiceBus.SqlServer.CompatibilityTests.csproj

Update test projects to NServiceBus 7.2.3 in release-4.3

---

src/NServiceBus.SqlServer.CompatibilityTests/NServiceBus.SqlServer.CompatibilityTests.csproj

Update test projects to NServiceBus 7.2.3 in release-5.0

---

src/NServiceBus.SqlServer.UnitTests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
src/NServiceBus.SqlServer/Queuing/TableBasedQueue.cs
src/NServiceBus.SqlServer/Receiving/SchemaVerification.cs

Backport of #624 for `release-4.3` branch

Non-clustered index on `RowVersion`

---

src/NServiceBus.SqlServer.UnitTests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.SqlServer/Queuing/SqlConstants.cs
src/NServiceBus.SqlServer/Queuing/TableBasedQueue.cs
src/NServiceBus.SqlServer/Receiving/SchemaVerification.cs

Backport of #624 for `release-5.0` branch

Non clustered index on `RowVersion`

---

src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs
src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs
src/NServiceBus.Transport.SqlServer/Receiving/SchemaVerification.cs

Backport of #624 for `release-6.0` branch

Non-clustered index on `RowVersion` column

---

src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.Transport.SqlServer/NServiceBus.Transport.SqlServer.csproj

Highlighting packages differences between `NServiceBus.SqlServer` and `NServiceBus.Transport.SqlServer`.

Improved Nuget descriptions to avoid package confusion

---

src/NServiceBus.Transport.SqlServer/Receiving/MessagePump.cs

Found while investigating #654 
The task tracking logic is not needed if you use the semaphore instead. 
Should be backported to `release-6.1`

Simplify message pump tracking logic

---

src/NServiceBus.Transport.SqlServer/Receiving/MessagePump.cs
src/NServiceBus.Transport.SqlServer/Receiving/QueuePeeker.cs

Complete the scope in the queue peeker and then delay if no messages found

---

src/NServiceBus.Transport.SqlServer/Receiving/MessagePump.cs

Simplify pump

---

src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs

Rasied https://github.com/Particular/docs.particular.net/pull/5001

Endpoint column cannot be null

---

src/NServiceBus.SqlServer.UnitTests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_receiving_messages.cs
src/NServiceBus.Transport.SqlServer.UnitTests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Transport.SqlServer/Receiving/MessagePump.cs
src/NServiceBus.Transport.SqlServer/Receiving/QueuePeekerOptions.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransportSettingsExtensions.cs

Related to #174 
Backporting of #710

Peek batch size in 6.2

---

src/NServiceBus.SqlServer.UnitTests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_receiving_messages.cs
src/NServiceBus.Transport.SqlServer.UnitTests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Transport.SqlServer/Receiving/MessagePump.cs
src/NServiceBus.Transport.SqlServer/Receiving/QueuePeekerOptions.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransportSettingsExtensions.cs
src/NServiceBus.Transport.SqlServer/obsoletes-v8.cs

Peek batch size config

---

src/NServiceBus.Transport.SqlServer.IntegrationTests/When_checking_schema.cs
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_dispatching_messages.cs
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_message_receive_takes_long.cs
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_receiving_messages.cs
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_using_ttbr.cs
src/NServiceBus.Transport.SqlServer.TransportTests/ConfigureSqlServerTransportInfrastructure.cs
src/NServiceBus.Transport.SqlServer/Queuing/MessageRow.cs
src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs
src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueueCache.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransport.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs

Cherry pick of https://github.com/Particular/NServiceBus.SqlServer/pull/714

Encrypt column cherry pick

---

src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.Transport.SqlServer/NServiceBus.Transport.SqlServer.csproj

Target framework update to netcoreapp2.1 as part of https://github.com/Particular/Exploration/issues/482

upgrade target framework

---

src/NServiceBus.Transport.SqlServer.IntegrationTests/When_receiving_messages.cs
src/NServiceBus.Transport.SqlServer/Receiving/MessageReceiver.cs
src/NServiceBus.Transport.SqlServer/Receiving/ProcessStrategy.cs
src/NServiceBus.Transport.SqlServer/Receiving/ProcessWithNativeTransaction.cs
src/NServiceBus.Transport.SqlServer/Receiving/ProcessWithNoTransaction.cs
src/NServiceBus.Transport.SqlServer/Receiving/ProcessWithTransactionScope.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs

relates to https://github.com/Particular/NServiceBus.SqlServer/pull/773

rename message receiving and processing members

---

src/NServiceBus.Transport.SqlServer.IntegrationTests/When_message_receive_takes_long.cs
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_receiving_messages.cs
src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs
src/NServiceBus.Transport.SqlServer/Receiving/QueuePeeker.cs

relates to https://github.com/Particular/NServiceBus.SqlServer/pull/773

fix TableBasedQueue.TryPeek signature

---

src/NServiceBus.Transport.SqlServer/Receiving/MessageReceiver.cs

relates to https://github.com/Particular/NServiceBus.SqlServer/pull/773
Since we dispose the token on line 108.

avoid object disposed exception in MessageReciver.Stop

---

src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
src/NServiceBus.SqlServer.TransportTests/NServiceBus.SqlServer.TransportTests.csproj
src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.Transport.SqlServer.AcceptanceTests/NServiceBus.Transport.SqlServer.AcceptanceTests.csproj
src/NServiceBus.Transport.SqlServer.IntegrationTests/NServiceBus.Transport.SqlServer.IntegrationTests.csproj
src/NServiceBus.Transport.SqlServer.TransportTests/NServiceBus.Transport.SqlServer.TransportTests.csproj
src/NServiceBus.Transport.SqlServer.UnitTests/NServiceBus.Transport.SqlServer.UnitTests.csproj
src/NServiceBus.Transport.SqlServer/Configuration/SqlConnectionFactory.cs
src/NServiceBus.Transport.SqlServer/DelayedDelivery/DueDelayedMessageProcessor.cs
src/NServiceBus.Transport.SqlServer/ExceptionExtensions.cs
src/NServiceBus.Transport.SqlServer/NServiceBus.Transport.SqlServer.csproj
src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs
src/NServiceBus.Transport.SqlServer/Receiving/ExpiredMessagesPurger.cs
src/NServiceBus.Transport.SqlServer/Receiving/MessageReceiver.cs
src/NServiceBus.Transport.SqlServer/Receiving/ProcessStrategy.cs
src/NServiceBus.Transport.SqlServer/Receiving/ProcessWithNativeTransaction.cs
src/NServiceBus.Transport.SqlServer/Receiving/ProcessWithNoTransaction.cs
src/NServiceBus.Transport.SqlServer/Receiving/ProcessWithTransactionScope.cs
src/NServiceBus.Transport.SqlServer/Receiving/QueuePeeker.cs
src/NServiceBus.Transport.SqlServer/Receiving/RepeatedFailuresOverTimeCircuitBreaker.cs
src/NServiceBus.Transport.SqlServer/Receiving/SchemaVerification.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs

as discussed with @andreasohlund

fix OCE catching, Task.Run, etc.

---

src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs
src/NServiceBus.Transport.SqlServer/Receiving/QueueCreator.cs

Addresses https://github.com/Particular/NServiceBus.SqlServer/issues/757

Backport queue creation lock release logic fixes

---

src/NServiceBus.Transport.SqlServer/Queuing/SqlCommandExtensions.cs
src/NServiceBus.Transport.SqlServer/Queuing/TableBasedQueue.cs

Backporting https://github.com/Particular/NServiceBus.SqlServer/pull/846 & https://github.com/Particular/NServiceBus.SqlServer/pull/851

Defend against TryPeek command returning null

---

src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_deferring_multiple_messages.cs
src/NServiceBus.Transport.SqlServer/DelayedDelivery/DelayedMessageTable.cs
src/NServiceBus.Transport.SqlServer/DelayedDelivery/DueDelayedMessageProcessor.cs

Fix delayed message table bug in original implementation

---

src/NServiceBus.Transport.SqlServer.AcceptanceTests/NServiceBus.Transport.SqlServer.AcceptanceTests.csproj
src/NServiceBus.Transport.SqlServer.TransportTests/NServiceBus.Transport.SqlServer.TransportTests.csproj

https://github.com/Particular/DeveloperExperience/issues/1516

Update to core 7.6

---

src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
src/NServiceBus.SqlServer.TransportTests/NServiceBus.SqlServer.TransportTests.csproj
src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.Transport.SqlServer.AcceptanceTests/NServiceBus.Transport.SqlServer.AcceptanceTests.csproj
src/NServiceBus.Transport.SqlServer.IntegrationTests/NServiceBus.Transport.SqlServer.IntegrationTests.csproj
src/NServiceBus.Transport.SqlServer.TransportTests/NServiceBus.Transport.SqlServer.TransportTests.csproj
src/NServiceBus.Transport.SqlServer.UnitTests/NServiceBus.Transport.SqlServer.UnitTests.csproj
src/NServiceBus.Transport.SqlServer/NServiceBus.Transport.SqlServer.csproj
src/NServiceBus.Transport.SqlServer/Receiving/MessageReceiver.cs

Part of https://github.com/Particular/DeveloperExperience/issues/1516

Implement ChangeConcurrency

---

src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs

Forward port of https://github.com/Particular/NServiceBus.SqlServer/pull/1028 from version 6.3.4.

Minimize deadlocks on moving delayed messages

---

src/NServiceBus.SqlServer.UnitTests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Transport.SqlServer.UnitTests/ApprovalFiles/APIApprovals.Approve.approved.txt
src/NServiceBus.Transport.SqlServer/Configuration/SqlServerTransportSettingsExtensions.cs

Reintroduce hybrid pub/sub mode

---

src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.SqlServer.IntegrationTests/NServiceBus.SqlServer.IntegrationTests.csproj
src/NServiceBus.SqlServer.TransportTests/NServiceBus.SqlServer.TransportTests.csproj
src/NServiceBus.SqlServer.UnitTests/NServiceBus.SqlServer.UnitTests.csproj
src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_using_column_encrypted_connection.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/When_using_encrypted_connection.cs
src/NServiceBus.Transport.SqlServer/NServiceBus.Transport.SqlServer.csproj
src/NServiceBus.Transport.SqlServer/Queuing/MessageRow.cs

Fixes https://github.com/Particular/NServiceBus.SqlServer/issues/1150

Use correct index position when not reading the message body as a stream

---

src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativeTimeouts/When_configured_to_purge_expired_messages_at_startup.cs
src/NServiceBus.Transport.SqlServer/Receiving/MessageReceiver.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs

Handle `PurgeOnStartup` and `ExpiredMessagePurger.PurgeOnStartup` correctly

---

src/NServiceBus.SqlServer.AcceptanceTests/NServiceBus.SqlServer.AcceptanceTests.csproj
src/NServiceBus.Transport.SqlServer.AcceptanceTests/NServiceBus.Transport.SqlServer.AcceptanceTests.csproj
src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativeTimeouts/When_configured_to_purge_expired_messages_at_startup.cs
src/NServiceBus.Transport.SqlServer/Receiving/MessageReceiver.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs

Backport #1225 to 7.0

---

src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj
src/NServiceBus.Transport.SqlServer/NServiceBus.Transport.SqlServer.csproj

CVE-2024-0056 https://github.com/advisories/GHSA-98g6-xh36-x2p7

CVE-2024-0056

---

src/NServiceBus.Transport.SqlServer/Addressing/QueueAddressTranslator.cs

Dictionary key type `Transport.QueueAddress` does not return a deterministic hash code which results in a memory leak for items with the same key.

Fix memory leak in translating logical addresses to SQL queue addresses

---

.github/workflows/ci.yml

This adds login for ACI to avoid throttling

Use docker login for ACI

---

src/NServiceBus.Transport.PostgreSql.AcceptanceTests/NServiceBus.Transport.PostgreSql.AcceptanceTests.csproj
src/NServiceBus.Transport.PostgreSql.TransportTests/NServiceBus.Transport.PostgreSql.TransportTests.csproj
src/NServiceBus.Transport.PostgreSql.UnitTests/NServiceBus.Transport.PostgreSql.UnitTests.csproj
src/NServiceBus.Transport.SqlServer.AcceptanceTests/NServiceBus.Transport.SqlServer.AcceptanceTests.csproj
src/NServiceBus.Transport.SqlServer.IntegrationTests/NServiceBus.Transport.SqlServer.IntegrationTests.csproj
src/NServiceBus.Transport.SqlServer.TransportTests/NServiceBus.Transport.SqlServer.TransportTests.csproj
src/NServiceBus.Transport.SqlServer.UnitTests/NServiceBus.Transport.SqlServer.UnitTests.csproj

This PR contains all changes related to NUnit4 upgrade including all required dependencies.
The following packages are checked for necessary upgrades but might not necessarily be in the change set if they are not present:
- NServiceBus
- NServiceBus.AcceptanceTesting
- NServiceBus.AcceptanceTests.Sources
- NServiceBus.PersistenceTests.Sources
- NServiceBus.TransportTests.Sources
- NUnit
In addition, some manual interventions are done when applicable.

Upgrading to NUnit4 including all required dependencies

---

src/NServiceBus.Transport.PostgreSql.TransportTests/ConfigurePostgreSqlTransportInfrastructure.cs
src/NServiceBus.Transport.PostgreSql.TransportTests/NServiceBusTransportTest.cs
src/NServiceBus.Transport.PostgreSql.TransportTests/When_delayed_delivery_disabled.cs
src/NServiceBus.Transport.PostgreSql/PostgreSqlTransportInfrastructure.cs

Backport of https://github.com/Particular/NServiceBus.SqlServer/pull/1423

Disabling delayed delivery throws exception on startup

---

src/NServiceBus.Transport.PostgreSql.TransportTests/NServiceBusTransportTest.cs
src/NServiceBus.Transport.PostgreSql.TransportTests/When_publishing_message.cs

Prepares the repo to use the next minor of NServiceBus core
See https://github.com/Particular/NServiceBus/pull/7161 for more details

Adjust test copied base class to prepare for it being removed once the next core minor is available

---

src/NServiceBus.Transport.Sql.Shared/Queuing/TableBasedQueue.cs
src/NServiceBus.Transport.SqlServer.AcceptanceTests/NativeTimeouts/When_configured_to_purge_expired_messages_at_startup.cs
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_checking_schema.cs
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_dispatching_messages.cs
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_message_receive_takes_long.cs
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_receiving_messages.cs
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_recoverable_column_is_removed.cs
src/NServiceBus.Transport.SqlServer.IntegrationTests/When_using_ttbr.cs
src/NServiceBus.Transport.SqlServer/Queuing/SqlServerConstants.cs
src/NServiceBus.Transport.SqlServer/Queuing/SqlTableBasedQueue.cs
src/NServiceBus.Transport.SqlServer/SqlServerTransportInfrastructure.cs

copy of the following to run tests:
- https://github.com/Particular/NServiceBus.SqlServer/pull/1440

Use SQL system catalog views to check for the presence of a Recoverable column

---

.github/workflows/ci.yml
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiCatalog/When_catalog_with_special_characters_configured_for_endpoint.cs
src/NServiceBus.Transport.SqlServer/Queuing/SqlServerConstants.cs

Quote the catalog name when preparing the send command text in SQL Server

---

.github/workflows/ci.yml
src/NServiceBus.Transport.SqlServer.AcceptanceTests/MultiCatalog/When_catalog_with_special_characters_configured_for_endpoint.cs
src/NServiceBus.Transport.SqlServer/Queuing/SqlServerConstants.cs

Release PR for 1461

---

src/NServiceBus.Transport.Sql.Shared/Receiving/MessageReceiver.cs

Swapping of the semaphore objects wasn't thread-safe and could result in resources to incorrectly managing lifetimes and cause multiple disposes on the same object or a missing dispose.

Make changing concurrency threadsafe

---

src/Scripts/Create-Databases.sql
src/Scripts/Reset-Database.sql

After seeing the docs PR I did a regex search on `CREATE.*INDEX` and noticed more files more misalignment.
Connects to:
- https://github.com/Particular/docs.particular.net/issues/7186
- https://github.com/Particular/docs.particular.net/pull/7189

Align with ~/src/NServiceBus.Transport.SqlServer/Queuing/SqlServerConstants.cs
